version: '3.8'

services:

  order-service:
    image: order-service
    build:
      context: ./order-service
      dockerfile: ./Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-order
    networks:
      - spring

  postgres-order:
    image: postgres:latest
    container_name: postgres-order-gbc
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=order-service
    volumes:
        - ./data/postgres/order-service:/data/postgres
        - ./init/postgres/order-service/init.sql/:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
        - spring

  product-service:
    image: product-service
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-gbc
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: unless-stopped
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    command: mongod --auth
    networks:
        - spring

networks:
    spring:
        driver: bridge
        
      #mongo-init.js is a file that contains the initial data to be inserted into the database and allows read and write
