version: '3.8'

services:
  api-gateway:
    image: api-gateway
    ports:
      - "8182:8182"
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery-service
    networks:
      - spring
  discovery-service:
    image: discovery-service
    build:
      context: ./discovery-service
      dockerfile: ./Dockerfile
    container_name: discovery-service
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      eureka.instance.hostname: discovery-service
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
    networks:
      - spring

  inventory-service:
    image: inventory-service
    build:
      context: ./inventory-service
      dockerfile: ./Dockerfile
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      eureka.instance.hostname: discovery-service
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
    depends_on:
      - postgres-inventory
      - discovery-service
    networks:
      - spring

  order-service:
    image: order-service
    build:
      context: ./order-service
      dockerfile: ./Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      eureka.instance.hostname: discovery-service
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
    depends_on:
      - postgres-order
      - discovery-service
    networks:
      - spring

  postgres-inventory:
    image: postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-service
    volumes:
      - ./data/postgres/order-service:/var/lib/postgres
      - ./init/postgres/inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgresdb-inventory
    networks:
        - spring

  postgres-order:
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-service
    volumes:
      - ./data/postgres/order-service:/var/lib/postgresql/data
      - ./init/postgres/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgresdb-order
    networks:
        - spring

  product-service:
    image: product-service
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      eureka.instance.hostname: discovery-service
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
    depends_on:
      - mongodb
      - discovery-service
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-gbc
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: unless-stopped
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    command: mongod --auth
    networks:
        - spring

networks:
    spring:
        driver: bridge
    mongo:
        driver: bridge
    postgres:
        driver: bridge
        
      #mongo-init.js is a file that contains the initial data to be inserted into the database and allows read and write
